(()=>{
'use strict';
const $=id=>document.getElementById(id),screens=['home','difficulty','maps','field'];
let selected='easy',current='home',map=null,images=[],stage=0;
const choices=[...document.querySelectorAll('[data-difficulty]')];
function wheelPaint(){const rect=$('wheel').getBoundingClientRect(),center=rect.top+rect.height/2;let closest=null,best=Infinity;for(const b of choices){const slot=b.parentElement.getBoundingClientRect(),distance=Math.abs(slot.top+slot.height/2-center),ratio=Math.min(1,distance/220);b.style.setProperty('--scale',String(1-.38*ratio));b.style.setProperty('--opacity',String(1-.6*ratio));b.classList.remove('center');if(distance<best){best=distance;closest=b}}closest?.classList.add('center')}
function show(name,push=true){current=name;for(const id of screens)$(id).hidden=id!==name;if(push)history.pushState({screen:name,difficulty:selected,stage},'','#'+name);if(name==='difficulty')requestAnimationFrame(()=>{const index=choices.findIndex(b=>b.dataset.difficulty===selected);$('wheel').scrollTop=Math.max(0,index)*132;wheelPaint()});if(name==='maps'){$('difficultyBadge').textContent=selected.toUpperCase();$('difficultyBadge').className='badge '+selected}if(name==='field')drawField();window.scrollTo(0,0)}
history.replaceState({screen:'home',difficulty:selected,stage:0},'','#home');
$('stageSelect').addEventListener('click',()=>show('difficulty'));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.back)));
choices.forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.difficulty;show('maps')}));$('wheel').addEventListener('scroll',wheelPaint,{passive:true});window.addEventListener('resize',()=>{if(current==='difficulty')wheelPaint();if(current==='field')drawField()});window.addEventListener('popstate',e=>{selected=e.state?.difficulty||'easy';stage=e.state?.stage||0;show(e.state?.screen||'home',false)});
const areas=[[6,6],[25,10],[10,32],[32,32]];
for(let i=0;i<4;i++){const button=document.createElement('button');button.className='map-card';button.innerHTML=`<span><strong>ステージ ${i+1}</strong><small>草原 ${['Ⅰ','Ⅱ','Ⅲ','Ⅳ'][i]}</small></span><canvas width="160" height="128" aria-label="草原マップのサムネイル"></canvas>`;button.addEventListener('click',()=>{stage=i;show('field')});$('mapList').append(button)}
function terrain(canvas,x,y,cols,rows){const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.fillStyle='#477544';c.fillRect(0,0,canvas.width,canvas.height);if(!map)return;const w=canvas.width/cols,h=canvas.height/rows;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const mx=(x+col)%map.width,my=(y+row)%map.height,id=map.tiles[my*map.width+mx],image=images[id];if(image)c.drawImage(image,col*w,row*h,w+1,h+1)}}
function drawField(){const canvas=$('fieldCanvas');canvas.width=540;canvas.height=Math.round(540*window.innerHeight/Math.min(window.innerWidth,540));$('fieldTitle').textContent=`${selected.toUpperCase()} · ステージ ${stage+1}`;terrain(canvas,...areas[stage],12,Math.ceil(canvas.height/45))}
async function load(){try{const response=await fetch('maps/clock-attack-grassland.json',{cache:'no-store'});if(!response.ok)throw Error();map=await response.json();images=await Promise.all(map.tileset.map(t=>new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src=t.image})));document.querySelectorAll('.map-card canvas').forEach((c,i)=>terrain(c,...areas[i],10,8));if(current==='field')drawField()}catch{document.querySelector('.maps .note').textContent='マップ画像を読み込めませんでした。画面遷移は確認できます。'}}load();
})();